defaults:
  - override hydra/job_logging: disabled

arm_server:
  fps: 50
  buf_time: 0.3
  v_max: [3.0, 3.0, 3.0]
  a_max: [15.0, 15.0, 15.0]
  j_max: [600.0, 600.0, 600.0]
  urdf: "../roarm_main/roarm_description/urdf/roarm_description.urdf"
  joints:
    [
      "base_link_to_link1",
      "link1_to_link2",
      "link2_to_link3",
      "link3_to_gripper_link",
    ]
  ik_joints: ["base_link_to_link1", "link1_to_link2", "link2_to_link3"]
  traj_time_rate: 0.5
