defaults:
  - override hydra/job_logging: disabled

arm_server:
  fps: 50
  buf_time: 0.3
  arm_serial: "Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_80adf99a68e4ee118a2091844c11a646"
  v_max: [1.0, 1.0, 1.0]
  a_max: [5.0, 5.0, 5.0]
  j_max: [150.0, 150.0, 150.0]
  vaj_factor: 1.0
  urdf: "../roarm_main/roarm_description/urdf/roarm_description.urdf"
  joints:
    [
      "base_link_to_link1",
      "link1_to_link2",
      "link2_to_link3",
      "link3_to_gripper_link",
    ]
  ik_joints: ["base_link_to_link1", "link1_to_link2", "link2_to_link3"]
  traj_time_rate: 0.5
